var express = require('express');
var router = express.Router();

// http://localhost:9000 is the URL generated by devServer
// configured in webpack
const getStaticAssetsPath = () =>
  process.env.NODE_ENV !== 'production' ? 'http://localhost:9000' : ''

/* GET home page. */
router.get('/', function(req, res, next) {
  // 
  res.render('index', {
    title: 'Express',
    staticAssetsPath: getStaticAssetsPath()
  });
});

router.get('/foo', function(req, res, next) {
  res.render('index')
});

module.exports = router;
